### ISSUE TITLE
Demo broke

### ISSUE THREAD

**Issue by kidGodzilla** [TemperWorks/Nucleus#1]
https://temperworks.github.io/Nucleus/index.html

Looks like there's supposed to be a css and a js bundle for the docs, which is no longer published to the Github pages branch.

(Just opening an issue as a note because the fix isn't obvious)

**Comment by YordiLorenzo** [comment]
@kidGodzilla thnx for the reminder, I'll fix this asap. In the meantime you could also try to perform a full build and submit a PR, would save me some time. Thnx!
